from controller.controller import Controller

c = Controller()
#c.crear_usuario()
#c.actualizar_usuarios() 
#c.borrar_usuario()
#c.leer_todo_usuarios()
#c.crear_admin()
#c.actualizar_admin()
#c.actualizar_admin()
#c.leer_todo_admin()
#c.crear_pelicula()
#c.borrar_pelicula()
#c.leer_todo_peliculas()
#c.crear_sala(2)
#c.borrar_sala()
#c.leer_salas()
#c.crear_horario()
#c.leer_preestrenos()
#c.borrar_horario()
#c.leer_estrenos()
#c.leer_asientos_usuario()
#c.crear_ticket()
#c.crear_sala_pelicula()
#c.borrar_sala_peli()
#c.leer_costo_pelicula()
#c.leer_asientos_sala()
c.start()
#c.leer_horario()
#c.leer_horario_peliculas()
#c.borrar_ticket()

#fields = (4,)
#vals = ('Michell Andrade', 'Atziri Michelle')
#m.actualizar_usuarios(fields, vals)
#usuario = m.leer_todo_usuarios()
#m.borrar_pelicula(6)
#m.crear_pelicula('yo antes de ti','ingles','NULL',50)
#m.crear_sala(3, 50, 'VIP')
#m.crear_asiento(2,2,2,'ocupado',60)
#m.borrar_sala(3)
#m.borrar_asiento(2,2)
#m.crear_ticket(2,3,180)

#m.crear_pelicula('avengers','ingles','NULL')
#m.crear_pelicula('Spiderman','español','NULL')
#m.crear_pelicula('yo antes de ti','ingles','NULL')

#m.crear_horario('2020-05-20',1,1,'Avengers','NULL')
#m.crear_horario('2020-05-20',2,2,'Spiderman','NULL')

#m.crear_sala(1,12,10,'3D')
#m.crear_sala(2,10, 10 ,'VIP')

#m.crear_asiento('A',7, 1, 1, 'ocupado')
#m.crear_asiento('D',6, 1, 1, 'apartado')

#m.crear_horario_pelicula('2020-05-20',1,'1:30')
#m.crear_horario_pelicula('2020-05-20',1,'5:30')
#m.crear_horario_pelicula('2020-05-20',2,'1:30')

#m.crear_sala_pelicula(1,1,60)
#m.crear_sala_pelicula(2,1,60)

#horario = m.leer_un_usuario(1)
#print(horario)

#m.close_db()